// This file is auto-generated by @hey-api/openapi-ts

import { type Options as ClientOptions, type TDataShape, type Client, formDataBodySerializer } from '@hey-api/client-fetch';
import type { SongCreateData, SongCreateResponse2, SongCreateError, SongGetData, SongGetResponse2, SongGetError, SongExportVideoData, SongExportVideoResponse, SongExportVideoError, HandleChatDataApiChatPostData, HandleChatDataApiChatPostError } from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Create New Song
 * Create a new song by uploading a Guitar Pro file.
 *
 * This endpoint accepts a Guitar Pro file, saves it using the configured storage service,
 * and creates a new tab entry in the tabs collection.
 */
export const songCreate = <ThrowOnError extends boolean = false>(options: Options<SongCreateData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<SongCreateResponse2, SongCreateError, ThrowOnError>({
        ...formDataBodySerializer,
        url: '/api/songs/new',
        ...options,
        headers: {
            'Content-Type': null,
            ...options?.headers
        }
    });
};

/**
 * Get Song By Id
 * Get a song by its ID.
 *
 * This endpoint retrieves a song's tab information including the tab ID and file reference.
 */
export const songGet = <ThrowOnError extends boolean = false>(options: Options<SongGetData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<SongGetResponse2, SongGetError, ThrowOnError>({
        url: '/api/songs/{song_id}',
        ...options
    });
};

/**
 * Export Song Video
 * Export a metronome video for a song.
 *
 * This endpoint takes a song ID and export settings, retrieves the song's tab data,
 * and generates a metronome video with visual timing cues for band practice.
 *
 * The video includes:
 * - Large measure counter
 * - Current section names (Intro, Verse, Chorus, etc.)
 * - Beat indicators with emphasis on beat 1
 * - Quarter note counter
 * - Visual metronome pendulum
 * - Audio metronome with different sounds for beat 1
 */
export const songExportVideo = <ThrowOnError extends boolean = false>(options: Options<SongExportVideoData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<SongExportVideoResponse, SongExportVideoError, ThrowOnError>({
        url: '/api/songs/export-video',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Chat with AI Assistant
 * Stream chat responses from OpenAI with tool calling support for weather information
 */
export const handleChatDataApiChatPost = <ThrowOnError extends boolean = false>(options: Options<HandleChatDataApiChatPostData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<unknown, HandleChatDataApiChatPostError, ThrowOnError>({
        url: '/api/chat',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};