// This file is auto-generated by @hey-api/openapi-ts

export type BodySongCreate = {
    /**
     * Guitar Pro file to upload
     */
    file: Blob | File;
};

export type ClientAttachment = {
    name: string;
    contentType: string;
    url: string;
};

export type ClientMessage = {
    role: string;
    content: string;
    experimental_attachments?: Array<ClientAttachment> | null;
    toolInvocations?: Array<ToolInvocation> | null;
};

/**
 * Response model for song creation.
 */
export type CreateSongResponse = {
    success: boolean;
    message: string;
    song_id?: string | null;
    tab_id?: string | null;
    file_reference?: FileReference | null;
};

/**
 * Reference to a file stored in a storage provider.
 */
export type FileReference = {
    /**
     * Storage provider name (e.g., 'local', 's3')
     */
    provider: string;
    /**
     * Provider-specific file reference/path
     */
    reference: string;
};

/**
 * Response model for getting a song by ID.
 */
export type GetSongResponse = {
    success: boolean;
    message: string;
    song_id?: string | null;
    tab_id?: string | null;
    file_reference?: FileReference | null;
};

export type HttpValidationError = {
    detail?: Array<ValidationError>;
};

/**
 * Chat request containing conversation messages.
 */
export type Request = {
    messages: Array<ClientMessage>;
};

export type ToolInvocation = {
    state: ToolInvocationState;
    toolCallId: string;
    toolName: string;
    args: unknown;
    result: unknown;
};

export type ToolInvocationState = 'call' | 'partial-call' | 'result';

export type ValidationError = {
    loc: Array<string | number>;
    msg: string;
    type: string;
};

export type SongCreateData = {
    body: BodySongCreate;
    path?: never;
    query?: never;
    url: '/api/songs/new';
};

export type SongCreateErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SongCreateError = SongCreateErrors[keyof SongCreateErrors];

export type SongCreateResponses = {
    /**
     * Successful Response
     */
    200: CreateSongResponse;
};

export type SongCreateResponse = SongCreateResponses[keyof SongCreateResponses];

export type GetSongByIdApiSongsSongIdGetData = {
    body?: never;
    path: {
        song_id: string;
    };
    query?: never;
    url: '/api/songs/{song_id}';
};

export type GetSongByIdApiSongsSongIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetSongByIdApiSongsSongIdGetError = GetSongByIdApiSongsSongIdGetErrors[keyof GetSongByIdApiSongsSongIdGetErrors];

export type GetSongByIdApiSongsSongIdGetResponses = {
    /**
     * Successful Response
     */
    200: GetSongResponse;
};

export type GetSongByIdApiSongsSongIdGetResponse = GetSongByIdApiSongsSongIdGetResponses[keyof GetSongByIdApiSongsSongIdGetResponses];

export type HandleChatDataApiChatPostData = {
    body: Request;
    path?: never;
    query?: {
        /**
         * Response protocol format
         */
        protocol?: string;
    };
    url: '/api/chat';
};

export type HandleChatDataApiChatPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type HandleChatDataApiChatPostError = HandleChatDataApiChatPostErrors[keyof HandleChatDataApiChatPostErrors];

export type HandleChatDataApiChatPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};